
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class internalMarksPage extends javax.swing.JFrame {

    /**
     * Creates new form internalMarksPage
     */
    public internalMarksPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backToMainPage = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        internalTable = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1264, 599));
        setPreferredSize(new java.awt.Dimension(1264, 599));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backToMainPage.setBackground(new java.awt.Color(255, 0, 0));
        backToMainPage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backToMainPage.setText("X");
        backToMainPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainPageActionPerformed(evt);
            }
        });
        getContentPane().add(backToMainPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, -1, 31));

        internalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "sub_id", "subject_name", "mentor_id", "mentee_id", "sem_no", "CIE_1", "CIE_2", "CIE_3", "finalMarks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        internalTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                internalTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(internalTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 800, -1));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 190, -1));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 190, -1));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField3.setText("jTextField3");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 190, -1));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField4.setText("jTextField4");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 190, -1));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField5.setText("jTextField5");
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 190, -1));

        jTextField6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField6.setText("jTextField6");
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, 30));

        jTextField7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField7.setText("jTextField7");
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, 30));

        jTextField8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField8.setText("jTextField8");
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("sub_id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 86, 120, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("subject_name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 153, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("mentor_id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 223, 120, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("mentee_id");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 293, 120, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("sem_no");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 353, 120, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("CIE_1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 422, 37, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("CIE_2");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 422, 37, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("CIE_3");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 422, 37, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToMainPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMainPageActionPerformed
        // TODO add your handling code here:
        this.toBack();
        setVisible(false);
        new mentorMainPage().toFront();
         new mentorMainPage().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_backToMainPageActionPerformed

    private void internalTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_internalTableMouseClicked
        // TODO add your handling code here:
        int row=internalTable.getSelectedRow();
        String sub_idCell=internalTable.getModel().getValueAt(row, 0).toString();
         String mentor_idCell=internalTable.getModel().getValueAt(row, 2).toString();
          String mentee_idCell=internalTable.getModel().getValueAt(row, 3).toString();
        try{
            Connection con=ConnectionProvider.getCon();
             
            String sql1="select sub_id,subject_name,mentor_id,mentee_id,sem_no,CIE_1,CIE_2,CIE_3,finalmarks from subject where sub_id='"+sub_idCell+"'and mentor_id='"+mentor_idCell+"' and mentee_id='"+mentee_idCell+"'";
             java.sql.PreparedStatement pst = con.prepareStatement(sql1);
                  java.sql.ResultSet rs =pst.executeQuery();
                  if(rs.next())
                  {
                     
                     jTextField1.setText(rs.getString("sub_id"));
                     jTextField2.setText(rs.getString("subject_name"));
                     jTextField3.setText(rs.getString("mentor_id"));
                    jTextField4.setText(rs.getString("mentee_id"));
                    jTextField5.setText(rs.getString("sem_no"));
                    jTextField6.setText(rs.getString("CIE_1"));
                    jTextField7.setText(rs.getString("CIE_2"));
                    jTextField8.setText(rs.getString("CIE_3"));
                     
                  }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_internalTableMouseClicked
      public void showinternalTableData(){
        String mid=jTextField3.getText();
             try{
                 Connection con=ConnectionProvider.getCon();
                 String sql="select sub_id,subject_name,mentor_id,mentee_id,sem_no,CIE_1,CIE_2,CIE_3,finalmarks from subject where mentor_id='"+mid+"'";
                 java.sql.PreparedStatement pst = con.prepareStatement(sql);
                  ResultSet rs =pst.executeQuery();
                  internalTable.setModel(DbUtils.resultSetToTableModel(rs));
             }   
             catch(Exception e){
                 e.printStackTrace();
             }
         }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
             String sub_idCell=jTextField1.getText();
              String mentor_idCell=jTextField3.getText();
               String mentee_idCell=jTextField4.getText();
            int CIE_1text=Integer.parseInt(jTextField7.getText());
            int CIE_2text=Integer.parseInt(jTextField6.getText());
            int CIE_3text=Integer.parseInt(jTextField8.getText());
            int finalMarks=CIE_1text+CIE_2text+CIE_3text;
             Connection con=ConnectionProvider.getCon();
             String updateCIE = "UPDATE subject SET CIE_1 = ?,CIE_2 = ? ,CIE_3=? ,finalmarks=?/3 WHERE sub_id=? and mentor_id=? and mentee_id = ? ";
//            String updateFinalMarks = "UPDATE subject SET finalmarks = (?)/3  WHERE sub_id = ? AND mentor_id = ? and mentee_id=?";
            java.sql.PreparedStatement ps1 = con.prepareStatement(updateCIE);
//             java.sql.PreparedStatement ps2 = con.prepareStatement(updateFinalMarks);
              ps1.setInt(1, CIE_1text);
               ps1.setInt(2, CIE_2text);
                ps1.setInt(3, CIE_3text);
                 ps1.setInt(4, finalMarks);
                 ps1.setString(5, sub_idCell);
                 ps1.setString(6, mentor_idCell);
                 ps1.setString(7, mentee_idCell);
                  ps1.executeUpdate();
//                  ps2.setInt(1, finalMarks);
//             
//                  ps2.setString(2, sub_idCell);
//                  ps2.setString(3, mentor_idCell);
//                  ps2.setString(4, mentee_idCell);
                  JOptionPane.showMessageDialog(null, "updated sucessfull");
                  showinternalTableData();
                  
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(internalMarksPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(internalMarksPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(internalMarksPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(internalMarksPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new internalMarksPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMainPage;
    public javax.swing.JTable internalTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
