import java.sql.*;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.PreparedStatement;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class menteeDetailsPage extends javax.swing.JFrame {

    /**
     * Creates new form menteeDetailsPage
     */
    public menteeDetailsPage() {
        initComponents();
         showTableData();
    }
    public  void clearTable(){
       jTextField1.setText(null);
       jTextField2.setText(null);
       jTextField4.setText(null);
      phnoText.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        phnoText = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1264, 647));
        setPreferredSize(new java.awt.Dimension(1264, 647));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(226, 241, 241));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 255, 255), null, null));
        jTable1.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "mentee_id", "mentee_name", "mentor_id", "address", "gender", "phnoNumber", "semester_no", "branch", "scheme"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 780, -1));

        jTextField1.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 185, 30));

        jTextField2.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 185, 30));

        jTextField4.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 185, 30));

        phnoText.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        getContentPane().add(phnoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 185, 30));

        jComboBox1.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jComboBox1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 185, 30));

        jComboBox2.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBox2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, 30));

        jComboBox3.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2021" }));
        jComboBox3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, 30));

        jComboBox4.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AIML", "CSE_A", "CSE_B", "CSE_C" }));
        jComboBox4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, -1, 30));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel1.setText("mentee_id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 20));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel2.setText("mentee_name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel3.setText("mentor_id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 110, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel4.setText("address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 110, 20));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel5.setText("gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 110, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel6.setText("phnoNumber");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 110, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel7.setText("sem, scheme,section");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 120, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, 30));

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, -1, 30));

        jButton3.setBackground(new java.awt.Color(0, 153, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, -1, 30));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 190, 30));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setText("X");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 20, 50, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 2, 36)); // NOI18N
        jLabel8.setText("DATA ENTRY  OF MENTEES");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 610, 40));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 100));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1260, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        try{
           Connection con=ConnectionProvider.getCon();
           Statement st=con.createStatement();
           String mentee_id=jTextField1.getText();
           String mentee_name=jTextField2.getText();
           String mentor_id=jTextField3.getText();
           String address=jTextField4.getText();
           String gender =jComboBox1.getSelectedItem().toString();
           int phnoNumber=Integer.parseInt(phnoText.getText());
            int sem_no =Integer.parseInt(jComboBox2.getSelectedItem().toString());
            int scheme=Integer.parseInt(jComboBox3.getSelectedItem().toString());
            String branch=jComboBox4.getSelectedItem().toString();
          
          
             String query1 = "INSERT INTO mentee VALUES ('" + mentee_id + "', '" + mentee_name + "', '" + mentor_id + "', '" + address + "', '" + gender + "', '" + phnoNumber + "',  '" + branch + "')";

            st.executeUpdate(query1);
             String query="insert into semester values('"+mentee_id+"' ,  '"+sem_no+"','"+scheme+"')";
          st.executeUpdate(query);
              JOptionPane.showMessageDialog(null, "insertion sucessfull");
               showTableData();
               clearTable();
        }
        catch(Exception e){
              JOptionPane.showMessageDialog(null, e);
        }
        showTableData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
           Connection con=ConnectionProvider.getCon();
           
           String mentee_id=jTextField1.getText();
           String mentee_name=jTextField2.getText();
           String mentor_id=jTextField3.getText();
           String address=jTextField4.getText();
           String gender =jComboBox1.getSelectedItem().toString();
           int phone_number=Integer.parseInt(phnoText.getText());
            int sem_no =Integer.parseInt(jComboBox2.getSelectedItem().toString());
            int scheme=Integer.parseInt(jComboBox3.getSelectedItem().toString());
            String branch=jComboBox4.getSelectedItem().toString();
            
               String updateSemester = "UPDATE semester SET sem_no = ? WHERE mentee_id = ? ";
            String updateMentee = "UPDATE mentee SET mentee_name = ?,address=?,gender= ?,phone_number= ?,branch= ? WHERE mentee_id = ? AND mentor_id = ?";
             try (PreparedStatement ps1 = con.prepareStatement(updateMentee);
                 PreparedStatement ps2 = con.prepareStatement(updateSemester);
                 ) {
          
       
        ps1.setString(1, mentee_name);
        ps1.setString(2, address);
        ps1.setString(3, gender);
        ps1.setInt(4, phone_number);
            ps1.setString(5, branch);
              ps1.setString(6, mentee_id);
                ps1.setString(7, mentor_id);
             ps1.executeUpdate();
              ps2.setInt(1, sem_no);
        ps2.setString(2, mentee_id);
        
        ps2.executeUpdate();
       JOptionPane.showMessageDialog(null, "updated sucessfull");
        showTableData();
        clearTable();
    } catch (SQLException e1) {
        e1.printStackTrace();
        JOptionPane.showMessageDialog(null, e1);
    }
            
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
    showTableData();
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row=jTable1.getSelectedRow();
        String Selection=jTable1.getModel().getValueAt(row, 0).toString();
        try{
             Connection con=ConnectionProvider.getCon();
             
            String sql1="select  m.mentee_id,m.mentee_name,m.mentor_id,m.address,m.gender,m.phone_number,s.sem_no,m.branch,s.scheme  from mentee m, semester s where m.mentee_id=s.mentee_id  and m.mentee_id='"+Selection+"'";
             PreparedStatement pst = con.prepareStatement(sql1);
                  ResultSet rs =pst.executeQuery();
                  if(rs.next())
                  {
                     
                     jTextField1.setText(rs.getString("mentee_id"));
                     jTextField2.setText(rs.getString("mentee_name"));
                     jTextField4.setText(rs.getString("address"));
                     jComboBox1.setSelectedItem(rs.getString("gender"));
                     phnoText.setText(rs.getString("phone_number"));
                     jComboBox2.setSelectedItem(rs.getString("sem_no"));
                     jComboBox3.setSelectedItem(rs.getString("branch"));
                     jComboBox4.setSelectedItem(rs.getString("scheme"));
                     
                  }
        }
        catch(Exception e){
            e.printStackTrace();
            
        }
         
         
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         int row1=jTable1.getSelectedRow();
        String Selection1=jTable1.getModel().getValueAt(row1, 0).toString();
         try{
             Connection con=ConnectionProvider.getCon();
             String sql2="DELETE m, s FROM mentee m INNER JOIN semester s ON m.mentee_id = s.mentee_id WHERE m.mentee_id ="+Selection1;
              PreparedStatement pst = con.prepareStatement(sql2);
              pst.execute();
                 JOptionPane.showMessageDialog(null, "deleted sucessfull");
                 showTableData();
         }
         catch(Exception e){
             e.printStackTrace();
             
         }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
      this.toBack();
        setVisible(false);
        new mentorMainPage().toFront();
         new mentorMainPage().setState(java.awt.Frame.NORMAL);
        
    }//GEN-LAST:event_jButton4ActionPerformed
    public void showTableData(){
        String mid=jTextField3.getText();
             try{
                 Connection con=ConnectionProvider.getCon();
                 String sql="select  m.mentee_id,m.mentee_name,m.mentor_id,m.address,m.gender,m.phone_number,s.sem_no,m.branch,s.scheme  from mentee m, semester s where m.mentee_id=s.mentee_id and mentor_id='"+mid+"'";
                 PreparedStatement pst = con.prepareStatement(sql);
                  ResultSet rs =pst.executeQuery();
                  jTable1.setModel(DbUtils.resultSetToTableModel(rs));
             }   
             catch(Exception e){
                 e.printStackTrace();
             }
         }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menteeDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menteeDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menteeDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menteeDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menteeDetailsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField phnoText;
    // End of variables declaration//GEN-END:variables
}
