
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class updateAttendance extends javax.swing.JFrame {

    /**
     * Creates new form updateAttendance
     */
    public updateAttendance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        updateAttendTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1271, 704));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateAttendTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "sub_id", "subject_name", "mentor_id", "mentee_id", "sem_no", "attendance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        updateAttendTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateAttendTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(updateAttendTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 800, -1));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 20, 40, 30));

        jTextField1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 210, -1));

        jTextField2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 210, -1));

        jTextField3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextField3.setText("jTextField3");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 210, -1));

        jTextField4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextField4.setText("jTextField4");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 210, -1));

        jTextField5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextField5.setText("jTextField5");
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 210, -1));

        jTextField6.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextField6.setText("jTextField6");
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 90, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton2.setText("update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, 190, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel1.setText("sub_id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 113, 140, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setText("subject_name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 193, 140, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel3.setText("mentor_id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 263, 140, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel4.setText("mentee_id");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 333, 140, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel5.setText("sem_no");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 410, 140, -1));

        jLabel6.setText("no of classes attended");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 480, 120, -1));

        jTextField7.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextField7.setText("jTextField7");
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, -1, -1));

        jTextField8.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextField8.setText("jTextField8");
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 100, -1));

        jLabel7.setText("total no of classes");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 100, -1));

        jLabel8.setText("attendance percentage");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         this.toBack();
        setVisible(false);
        new mentorMainPage().toFront();
         new mentorMainPage().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateAttendTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateAttendTableMouseClicked
        // TODO add your handling code here:
        try{
           int row=updateAttendTable.getSelectedRow();
        String sub_idCell=updateAttendTable.getModel().getValueAt(row, 0).toString();
         String mentor_idCell=updateAttendTable.getModel().getValueAt(row, 2).toString();
          String mentee_idCell=updateAttendTable.getModel().getValueAt(row, 3).toString(); 
          Connection con=ConnectionProvider.getCon();
          String sql1="select sub_id,subject_name,mentor_id,mentee_id,sem_no,attendance from subject where sub_id='"+sub_idCell+"'and mentor_id='"+mentor_idCell+"' and mentee_id='"+mentee_idCell+"'";
          java.sql.PreparedStatement pst = con.prepareStatement(sql1);
                  java.sql.ResultSet rs =pst.executeQuery();
                  if(rs.next())
                  {
                     
                     jTextField1.setText(rs.getString("sub_id"));
                     jTextField2.setText(rs.getString("subject_name"));
                     jTextField3.setText(rs.getString("mentor_id"));
                    jTextField4.setText(rs.getString("mentee_id"));
                    jTextField5.setText(rs.getString("sem_no"));
                    jTextField8.setText(rs.getString("attendance"));
                   
                     
                  }
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_updateAttendTableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String sub_idCell=jTextField1.getText();
        String mentor_idCell=jTextField3.getText();
        String mentee_idCell=jTextField4.getText();
        double totalAttend=Double.valueOf(jTextField7.getText());
         double Attended=Double.valueOf(jTextField6.getText());
         if(totalAttend >= Attended){
     if((totalAttend > 0 && totalAttend<=50) && (Attended > 0 && Attended<=50)) {
    double totalpercent = (Attended/totalAttend)*100;
    jTextField8.setText(""+totalpercent);
     
        try {
            Connection con=ConnectionProvider.getCon();
      String updateAttendance = "UPDATE subject SET attendance=? WHERE sub_id=? and mentor_id=? and mentee_id = ? ";
            java.sql.PreparedStatement ps1 = con.prepareStatement(updateAttendance);
            ps1.setDouble(1, totalpercent);
            ps1.setString(2, sub_idCell);
                 ps1.setString(3, mentor_idCell);
                 ps1.setString(4, mentee_idCell);
             ps1.executeUpdate();
             showAttendTable();
              JOptionPane.showMessageDialog(null, "updated sucessfull");
        } 
        catch (SQLException ex) {
            Logger.getLogger(updateAttendance.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
     else{
          JOptionPane.showMessageDialog(null, "no classes cant br 0 or 50");
     }
         }
         else{
             JOptionPane.showMessageDialog(null, "no of classes attended cannot be greater than total classses");
         }
    }//GEN-LAST:event_jButton2ActionPerformed
     public void showAttendTable(){
         String mid=jTextField3.getText();
             try{
                 Connection con=ConnectionProvider.getCon();
                 String sql="select sub_id,subject_name,mentor_id,mentee_id,sem_no,attendance from subject where mentor_id='"+mid+"'";
                 java.sql.PreparedStatement pst = con.prepareStatement(sql);
                  java.sql.ResultSet rs =pst.executeQuery();
                  updateAttendTable.setModel(DbUtils.resultSetToTableModel(rs));
             }   
             catch(Exception e){
                 e.printStackTrace();
             }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    public javax.swing.JTable updateAttendTable;
    // End of variables declaration//GEN-END:variables
}
